# Generated by Selenium IDE
import time
import os
import pytest
import random
import requests
import json
import string
from playwright.sync_api import sync_playwright
from openai import OpenAI
from PIL import Image
from dotenv import load_dotenv

#Keys

load_dotenv()

# Debug-Ausgaben
print("Umgebungsvariablen:")
print(f"GOOGLE_BOOKS_API_KEY: {os.getenv('GOOGLE_BOOKS_API_KEY')}")
print(f"OPENAI_API_KEY: {os.getenv('OPENAI_API_KEY')}")
print(f"EMAIL: {os.getenv('EMAIL')}")
print(f"PASSWORD: {os.getenv('PASSWORD')}")

api_key = os.getenv("GOOGLE_BOOKS_API_KEY")  # Google Books API Key

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY")) # OpenAI API Key



# def generate_random_keywords(n=50):
#     """
#     Generiert eine Liste von n zufälligen deutschen Wörtern.
    
#     :param n: Anzahl der zu generierenden Wörter.
#     :return: Liste von Wörtern.
#     """
#     url = "https://random-word-api.herokuapp.com/word"
#     params = {"number": n, "lang": "de"}
#     response = requests.get(url, params=params)
    
#     if response.status_code == 200:
#         words = response.json()
#         return words
#     else:
#         print(f"Fehler: {response.status_code} - {response.text}")
#         return []

# Funktion zum Generieren eines Bildes aus einem Textprompt
def generate_image_from_prompt(short_plot, client):
    client = client

    response = client.images.generate(
        model="dall-e-3",  # Bestes verfügbares Bildgenerierungsmodell
        prompt=f"""Erstelle ein künstlerisches, hochwertiges Bild basierend auf dieser Geschichte: {short_plot}
        
        Wichtige Anforderungen:
        - Keine Texte oder Wörter im Bild
        - Fokussiere auf die wichtigste Szene oder den emotionalsten Moment
        - Verwende eine ansprechende Komposition
        - Achte auf Details und Atmosphäre
        - Wähle passende Farben und Stimmung
        - Erstelle ein Bild im Stil eines professionellen Buchcovers
        - Stelle sicher, dass das Bild die Essenz der Geschichte einfängt""",
        size="1024x1024",
        quality="standard",
        n=1,
    )
    image_url = response.data[0].url
    print(f"Bild-URL: {image_url}")
    return image_url
    


def generate_chapter_title(story_description):
    completion = client.chat.completions.create(
        model="gpt-4-1106-preview",  # GPT-4 Turbo
        messages=[
            {"role": "system", "content": """Du bist ein Experte für kreative Titel.
            Deine Titel sind:
            - Einprägsam und originell
            - Neugierig machend
            - Passend zum Inhalt
            - Nicht zu lang
            - Mit emotionalem Impact
            
            Ein guter Titel sollte:
            - Die Essenz der Geschichte einfangen
            - Neugier wecken
            - Zum Weiterlesen anregen
            - Die Stimmung der Geschichte widerspiegeln"""},
            {
                "role": "user",
                "content": f"""Generiere einen fesselnden Titel für eine Geschichte basierend auf: {story_description}
                
                Wichtige Anforderungen:
                - Maximal 6 Wörter
                - Keine Anführungszeichen
                - Nur Wörter aus der Beschreibung verwenden
                - Der Titel soll neugierig machen
                - Der Titel soll die Stimmung der Geschichte einfangen
                - Der Titel soll zum Inhalt passen
                - Der Titel soll emotional ansprechend sein"""
            }
        ]
    )
    return completion.choices[0].message.content


def generate_short_plot(story_description):
    completion = client.chat.completions.create(
        model="gpt-4-1106-preview",  # GPT-4 Turbo
        messages=[
            {"role": "system", "content": """Du bist ein erfahrener Geschichtenerzähler mit folgenden Fähigkeiten:
            - Erstellung fesselnder Geschichten mit klarer Struktur
            - Entwicklung lebendiger Charaktere
            - Schreiben natürlicher Dialoge
            - Aufbau von Spannung und Emotion
            - Schaffen einer immersiven Atmosphäre
            
            Deine Geschichten folgen dieser Struktur:
            1. Einleitung: Einführung der Hauptfigur und des Settings
            2. Aufbau: Entwicklung des Konflikts oder der Herausforderung
            3. Höhepunkt: Die entscheidende Wendung oder Aktion
            4. Auflösung: Eine befriedigende Lösung oder Erkenntnis
            
            Stilistische Merkmale:
            - Lebendige Beschreibungen
            - Abwechslungsreiche Satzlängen
            - Authentische Dialoge
            - Emotionale Tiefe
            - Klare Absätze für bessere Lesbarkeit"""},
            {
                "role": "user",
                "content": f"""Erstelle eine fesselnde Geschichte basierend auf: {story_description}
                
                Wichtige Anforderungen:
                - Schreibe maximal 400 Wörter
                - Verwende die vorgegebene Struktur (Einleitung, Aufbau, Höhepunkt, Auflösung)
                - Erstelle mindestens einen interessanten Charakter mit Persönlichkeit
                - Baue mindestens einen natürlichen Dialog ein
                - Beschreibe die Umgebung und Stimmung detailliert
                - Verwende verschiedene Satzlängen für einen flüssigen Lesefluss
                - Teile den Text in sinnvolle Absätze
                - Baue Spannung auf
                - Achte auf einen logischen Handlungsverlauf
                - Verwende bildhafte Sprache
                - Schreibe in einem leicht lesbaren, aber ansprechenden Stil"""
            }
        ]
    )
    return completion.choices[0].message.content

def click_share_on_storyone_button(driver):
    try:
        # Versuche, das Element mit CSS-Selektor zu finden und zu klicken
        button = driver.find_element(By.CSS_SELECTOR, "div.writing-default-footer__button-container__inner > button.button.button--style--primary.button--size--default")
        button.click()
    except:
        try:
            # Fallback: Versuche, das Element mit relativem XPath zu finden und zu klicken
            button = driver.find_element(By.XPATH, "//button[.//div[text()='Share on StoryOne']]")
            button.click()
        except:
            try:
                # Fallback: Versuche, das Element mit absolutem XPath zu finden und zu klicken
                button = driver.find_element(By.XPATH, "/html/body/div[1]/div[3]/div/section/footer/div/div[2]/div/button[3]")
                button.click()
            except Exception as e:
                print(f"Element konnte nicht gefunden oder angeklickt werden: {e}")


def click_save_button(driver):
    try:
        # Versuche, das Element mit CSS-Selektor zu finden und zu klicken
        button = driver.find_element(By.CSS_SELECTOR, ".modal__footer > button:nth-child(2)")
        button.click()
    except:
        try:
            # Fallback: Versuche, das Element mit relativem XPath zu finden und zu klicken
            button = driver.find_element(By.XPATH, "//button[contains(@class, 'button') and .//span[text()='Save']]")
            button.click()
        except:
            try:
                # Fallback: Versuche, das Element mit absolutem XPath zu finden und zu klicken
                button = driver.find_element(By.XPATH, "/html/body/div[2]/div[2]/div/div[2]/button[2]")
                button.click()
            except Exception as e:
                print(f"Element konnte nicht gefunden oder angeklickt werden: {e}")

def click_novels_and_stories_span(driver):
    try:
        # Versuche, das Element mit CSS-Path zu finden und zu klicken
        span_element = driver.find_element(By.CSS_SELECTOR, "fieldset.radio-button:nth-child(1) > label:nth-child(1) > span:nth-child(3)")
        span_element.click()
    except:
        try:
            # Fallback: Versuche, das Element mit absolutem XPath zu finden und zu klicken
            span_element = driver.find_element(By.XPATH, "/html/body/div[2]/div[2]/div/div[1]/div[2]/div[2]/div[2]/fieldset[1]/label/span[1]")
            span_element.click()
        except Exception as e:
            print(f"Element konnte nicht gefunden oder angeklickt werden gligluizguk: {e}")
        try:
            # Fallback: Versuche, das Element mit relativem XPath und schwachen Bedingungen zu finden und zu klicken
            span_element = driver.find_element(By.XPATH, "//span[contains(@class, 'radio-symbol')]")
            span_element.click()
        except Exception as e:
            print(f"Element konnte nicht gefunden oder angeklickt werdenälkälköi: {e}")
        try:
            # Fallback: Versuche, das Element mit relativem XPath zu finden und zu klicken
            span_element = driver.find_element(By.XPATH, "//span[contains(text(), 'Novels')]")
            span_element.click()
        except:
            try:
                # Fallback: Versuche, das Element mit absolutem XPath zu finden und zu klicken
                span_element = driver.find_element(By.XPATH, "/html/body/div[2]/div[2]/div/div[1]/div[2]/div[2]/div[2]/fieldset[1]/label/span[1]")
                span_element.click()
            except Exception as e:
                print(f"Element konnte nicht gefunden oder angeklicktljhljhgljhgljhg werden: {e}")

def click_add_genre_button(driver):
    try:
        # Versuche, das Element mit CSS-Path zu finden und zu klicken
        button = driver.find_element(By.CSS_SELECTOR, "div.gap-03:nth-child(2) > div:nth-child(2) > div:nth-child(1) > button:nth-child(2) > div:nth-child(1)")
        button.click()
    except:
        try:
            # Fallback: Versuche, das Element mit relativem XPath zu finden und zu klicken
            button = driver.find_element(By.XPATH, "//div[contains(@class, 'button__inner') and text()='Add Genre']")
            button.click()
        except:
            try:
                # Fallback: Versuche, das Element mit absolutem XPath zu finden und zu klicken
                button = driver.find_element(By.XPATH, "/html/body/div[2]/div[2]/div/div[1]/div[2]/div[2]/div/button/div")
                button.click()
            except Exception as e:
                print(f"Element konnte nicht gefunden oder angeklickt werden: {e}")

def click_detailsbox_button(driver):
    try:
        # Versuche, das Element mit CSS-Selektor zu finden und zu klicken
        button = driver.find_element(By.CSS_SELECTOR, ".detailsbox__absolute-btn")
        button.click()
    except:
        try:
            # Fallback: Versuche, das Element mit relativem XPath zu finden und zu klicken
            button = driver.find_element(By.XPATH, "//button[contains(@class, 'detailsbox')]")
            button.click()
        except: 
            try:
                # Fallback: Versuche, das Element mit absolutem XPath zu finden und zu klicken
                button = driver.find_element(By.XPATH, "/html/body/div[1]/div[3]/div/section/section/div[1]/div[1]/article/div/button")
                button.click()
            except Exception as e:
                print(f"Element konnte nicht gefunden oder angeklickt werden: {e}")


def click_done_button(driver):
    """Versucht, den 'Done'-Button beim Bildupload zu finden und zu klicken."""
    try:
        done_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".modal__footer__actions > button:nth-child(2)"))
        )
        done_button.click()
        return True
    except Exception as e:
        print(f"Fehlgeschlagen: CSS-Selektor: nth-child -> {e}")
    
    return False


def upload_image(driver, image_url):
    """Versucht, das Upload-Element zu finden und die Datei von einer URL hochzuladen."""
    try:
        # Warte und finde das Element
        file_input = WebDriverWait(driver, 20).until(
            EC.presence_of_element_located((By.XPATH, "//input[@type='file']"))
        )
        # Datei von URL herunterladen und temporär speichern
        response = requests.get(image_url)
        temp_file_path = "/tmp/temp_image.jpg"
        with open(temp_file_path, 'wb') as temp_file:
            temp_file.write(response.content)
        
        # Erhöhe die Bildqualität stark
        with Image.open(temp_file_path) as img:
            img = img.resize((img.width * 2, img.height * 2), Image.LANCZOS)
            img.save(temp_file_path, dpi=(400, 400))
        
        # Datei hochladen
        file_input.send_keys(temp_file_path)
        return True
    except Exception as e:
        print(f"Fehlgeschlagen: XPath mit `type='file'` -> {e}")

# Funktion zum Versuch, auf den Upload-Tab zu klicken
def click_upload_tab(driver):
    try:
        upload_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, "//a[@role='tab' and text()='Upload']"))
        )
        upload_button.click()
    except Exception as e:
        print(f"Fehlgeschlagen: XPath mit Textinhalt -> {e}")


def close_popup_if_present(driver):
    try:
        close_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".overlay__close"))
        )
        close_button.click()
    except:
        pass

def generate_story_prompt():
    """
    Generiert einen kohärenten, aber zufälligen Story-Prompt.
    Kombiniert verschiedene Elemente zu einer interessanten Geschichte.
    Deckt alle Genres ab: Sci-Fi, Fantasy, Krimi, Thriller, Drama, Komödie, etc.
    """
    # Verschiedene Story-Elemente
    settings = [
        # Moderne Settings
        "in einem trendigen Co-Working Space", "in einer versteckten Bar", "in einem Luxushotel",
        "in einem verlassenen Einkaufszentrum", "in einem U-Bahn-Tunnel", "in einem Hochhaus",
        "in einem verschneiten Skigebiet", "in einem überfüllten Flughafen", "in einem geheimen Labor",
        "in einem versteckten Bunker", "in einem alten Kino", "in einem verlassenen Vergnügungspark",
        
        # Sci-Fi Settings
        "auf einer Raumstation", "in einer virtuellen Realität", "in einer alternativen Zukunft",
        "in einer künstlichen Intelligenz", "in einer Quantenwelt", "in einer Zeitmaschine",
        "auf einem fremden Planeten", "in einer Dystopie", "in einer post-apokalyptischen Welt",
        
        # Fantasy Settings
        "in einer magischen Dimension", "in einem verzauberten Wald", "in einer Unterwasserwelt",
        "in einer Parallelwelt", "in einem magischen Königreich", "in einer mythischen Stadt",
        
        # Natur Settings
        "in einem tropischen Regenwald", "in einer Wüste", "auf einem Gletscher",
        "in einem Korallenriff", "in einer Höhle", "auf einem Vulkan",
        
        # Urban Settings
        "in einer Großstadt", "in einem Vorort", "in einem Slum",
        "in einem Nobelviertel", "in einem Industriegebiet", "in einem Hafen"
    ]
    
    characters = [
        # Moderne Charaktere
        "ein erfolgreicher Tech-Entrepreneur", "eine investigative Journalistin", "ein genialer Hacker",
        "eine berühmte Influencerin", "ein mysteriöser Künstler", "ein ehemaliger Spion",
        "eine ambitionierte Anwältin", "ein verrückter Wissenschaftler", "eine mutige Aktivistin",
        "ein talentierter Musiker", "ein geheimnisvoller Detektiv", "eine geniale Programmiererin",
        
        # Alltagscharaktere
        "ein Taxifahrer", "eine Barista", "ein Postbote",
        "eine Krankenschwester", "ein Lehrer", "ein Koch",
        
        # Ungewöhnliche Charaktere
        "ein Zeitreisender", "ein Alien", "ein Android",
        "ein Geist", "ein Mutant", "ein Superheld",
        
        # Professionelle Charaktere
        "ein Chirurg", "ein Architekt", "ein Psychologe",
        "ein Polizist", "ein Politiker", "ein Anwalt"
    ]
    
    conflicts = [
        # Moderne Konflikte
        "muss eine Verschwörung aufdecken", "kämpft gegen eine KI-Bedrohung", "versucht einen Hackerangriff zu stoppen",
        "muss ein Unternehmen retten", "kämpft gegen Korruption", "versucht eine Pandemie zu verhindern",
        "muss eine Geheimwaffe zerstören", "kämpft gegen Cyberkriminalität", "versucht eine Revolution zu starten",
        
        # Persönliche Konflikte
        "muss eine schwierige Entscheidung treffen", "kämpft gegen eine Sucht", "versucht eine Beziehung zu retten",
        "muss mit einem Trauma umgehen", "kämpft gegen Vorurteile", "versucht sich selbst zu finden",
        
        # Gesellschaftliche Konflikte
        "muss gegen Ungerechtigkeit kämpfen", "versucht die Umwelt zu retten", "kämpft für Menschenrechte",
        "muss eine Gemeinschaft retten", "versucht Frieden zu stiften", "kämpft gegen Diskriminierung",
        
        # Übernatürliche Konflikte
        "muss ein magisches Artefakt finden", "kämpft gegen eine dunkle Macht", "versucht die Zeit zu ändern",
        "muss ein Portal schließen", "kämpft gegen ein Monster", "versucht eine Prophezeiung zu erfüllen"
    ]
    
    themes = [
        # Moderne Themen
        "über Technologie und Menschlichkeit", "über Social Media und Identität", "über Klimawandel und Verantwortung",
        "über künstliche Intelligenz und Ethik", "über Globalisierung und Kultur", "über Digitalisierung und Privatsphäre",
        
        # Gesellschaftliche Themen
        "über Macht und Korruption", "über Gerechtigkeit und Gleichheit", "über Freiheit und Sicherheit",
        "über Tradition und Fortschritt", "über Individualität und Konformität", "über Armut und Reichtum",
        
        # Persönliche Themen
        "über Liebe und Verlust", "über Freundschaft und Verrat", "über Familie und Identität",
        "über Träume und Realität", "über Vergangenheit und Zukunft", "über Leben und Tod",
        
        # Philosophische Themen
        "über Gut und Böse", "über Wahrheit und Lüge", "über Schicksal und freier Wille",
        "über Realität und Illusion", "über Wissen und Weisheit", "über Glaube und Wissenschaft"
    ]
    
    # Zufällige Auswahl der Elemente
    setting = random.choice(settings)
    character = random.choice(characters)
    conflict = random.choice(conflicts)
    theme = random.choice(themes)
    
    # Zusammenstellung des Prompts
    prompt = f"Eine Geschichte {setting}, in der {character} {conflict} {theme}."
    
    return prompt

if __name__ == "__main__":
    for i in range(1):
        try:
            # Testdaten statt API-Aufrufe
            book_description = "Eine Testgeschichte"
            chapter_title = "Test-Titel"
            short_plot = "Dies ist ein Test-Plot für die Automatisierung."
            bild = "https://example.com/test-image.jpg"  # Dummy-URL
            
            print(f"Test-Prompt: {book_description}")
            print(f"Test-Titel: {chapter_title}")
            print(f"Test-Geschichte:\n{short_plot}")
            
            # Playwright Setup
            user_input = input("Soll der Browser in Zeitlupe ausgeführt werden? (yes/no) [no]: ").strip().lower()
            if user_input == "yes":
                slow_mo_value = 500
            else:
                slow_mo_value = None

            browser = None
            try:
                with sync_playwright() as p:
                    browser = p.chromium.launch(headless=False, slow_mo=slow_mo_value)
                    context = browser.new_context()
                    page = context.new_page()
                    
                    # Navigate to StoryOne
                    page.goto("https://www.story.one/en/")
                    page.set_viewport_size({"width": 1920, "height": 1080})

                    # Login
                    page.click("text=Login/Signup")
                    page.fill("input[name='login-email']", os.getenv("EMAIL"))
                    page.fill("input[name='login-password']", os.getenv("PASSWORD"))
                    page.click("text=Login")
                    page.wait_for_load_state("networkidle")

                    # Handle cookies if present
                    try:
                        page.click("button:has-text('Accept')", timeout=5000)
                    except:
                        pass

                    # Click on draft
                    page.click("text=Draft")
                    page.wait_for_load_state("networkidle")

                    # Select story type
                    try:
                        page.click("text=Stories")
                    except:
                        page.click("span:has-text('Stories')")
                    page.wait_for_load_state("networkidle")

                    # Click write story
                    try:
                        page.click("text=Write Story")
                    except:
                        page.click("a:has-text('Write Story')")
                    page.wait_for_load_state("networkidle")

                    # Fill in title
                    page.fill("textarea[name='Title']", chapter_title)

                    # Click to write story
                    page.click("button:has-text('Write')")
                    page.wait_for_load_state("networkidle")

                    # Fill in story content
                    page.fill("div[contenteditable='true']", short_plot)
                    page.keyboard.press("Control+A")
                    page.keyboard.press("Control+C")
                    page.keyboard.press("Control+V")

                    # Go back
                    page.click("text=Back")
                    page.wait_for_load_state("networkidle")

                    # Upload image
                    page.click("button.edit-image-button__button")
                    page.click("text=Upload")
                    
                    # Test-Bild erstellen
                    temp_file_path = "/tmp/test_image.jpg"
                    with Image.new('RGB', (100, 100), color='red') as img:
                        img.save(temp_file_path)
                    
                    # Upload the image
                    page.set_input_files("input[type='file']", temp_file_path)
                    page.click("text=Done")
                    page.wait_for_load_state("networkidle")

                    # Add genre
                    page.click("button:has-text('Add Genre')")
                    page.click("text=Novels and Stories")
                    page.click("button:has-text('Save')")
                    page.wait_for_load_state("networkidle")

                    # Share on StoryOne
                    page.click("button:has-text('Share on StoryOne')")
                    page.wait_for_load_state("networkidle")

                    # Wait before closing
                    time.sleep(10)
                    print("Browser wird geschlossen...")
                    browser.close()
            except Exception as e:
                print(f"Fehler: {e}")
                if browser:
                    print("Browser wird geschlossen...")
                    browser.close()

        except Exception as e:
            print(f"Fehler: {e}")
            time.sleep(60)
            pass