# Generated by Selenium IDE
import time
import os
import pytest
import random
import requests
import json
import string
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
from openai import OpenAI
from PIL import Image
from dotenv import load_dotenv

#Keys

load_dotenv()

# Debug-Ausgaben
print("Umgebungsvariablen:")
print(f"GOOGLE_BOOKS_API_KEY: {os.getenv('GOOGLE_BOOKS_API_KEY')}")
print(f"OPENAI_API_KEY: {os.getenv('OPENAI_API_KEY')}")
print(f"EMAIL: {os.getenv('EMAIL')}")
print(f"PASSWORD: {os.getenv('PASSWORD')}")

api_key = os.getenv("GOOGLE_BOOKS_API_KEY")  # Google Books API Key

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY")) # OpenAI API Key



# def generate_random_keywords(n=50):
#     """
#     Generiert eine Liste von n zufälligen deutschen Wörtern.
    
#     :param n: Anzahl der zu generierenden Wörter.
#     :return: Liste von Wörtern.
#     """
#     url = "https://random-word-api.herokuapp.com/word"
#     params = {"number": n, "lang": "de"}
#     response = requests.get(url, params=params)
    
#     if response.status_code == 200:
#         words = response.json()
#         return words
#     else:
#         print(f"Fehler: {response.status_code} - {response.text}")
#         return []

# Funktion zum Generieren eines Bildes aus einem Textprompt
def generate_image_from_prompt(short_plot, client):
    client = client

    response = client.images.generate(
        model="dall-e-3",
        prompt=f" Never put text on your picture. Do not write anything on the image. Make image based on the following: {short_plot}",
        size="1024x1024",
        quality="standard",
        n=1,
    )
    image_url = response.data[0].url
    print(f"Bild-URL: {image_url}")
    return image_url
    


def generate_chapter_title(story_description):
    completion = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "Du bist ein hilfreicher Assistent."},
            {
                "role": "user",
                "content": f"Schreibe auf Deutsch. Generiere einen guten Kapitel-Titel. Schreibe nur den Titel, nichts anderes. Verwende nicht mehr als sechs Wörter. Setze ihn niemals in Anführungszeichen. Nutze für den Titel nur Wörter aus: {story_description}."
            }
        ]
    )
    return completion.choices[0].message.content


def generate_short_plot(story_description):
    completion = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "Du bist ein hilfreicher Assistent."},
            {
                "role": "user",
                "content": f"Schreibe 400 Wörter lang. Schreibe auf Deutsch. Erstelle den Text basierend auf folgende Beschreibung: {story_description}."
            }
        ]
    )
    return completion.choices[0].message.content

def click_share_on_storyone_button(driver):
    try:
        # Versuche, das Element mit CSS-Selektor zu finden und zu klicken
        button = driver.find_element(By.CSS_SELECTOR, "div.writing-default-footer__button-container__inner > button.button.button--style--primary.button--size--default")
        button.click()
    except:
        try:
            # Fallback: Versuche, das Element mit relativem XPath zu finden und zu klicken
            button = driver.find_element(By.XPATH, "//button[.//div[text()='Share on StoryOne']]")
            button.click()
        except:
            try:
                # Fallback: Versuche, das Element mit absolutem XPath zu finden und zu klicken
                button = driver.find_element(By.XPATH, "/html/body/div[1]/div[3]/div/section/footer/div/div[2]/div/button[3]")
                button.click()
            except Exception as e:
                print(f"Element konnte nicht gefunden oder angeklickt werden: {e}")


def click_save_button(driver):
    try:
        # Versuche, das Element mit CSS-Selektor zu finden und zu klicken
        button = driver.find_element(By.CSS_SELECTOR, ".modal__footer > button:nth-child(2)")
        button.click()
    except:
        try:
            # Fallback: Versuche, das Element mit relativem XPath zu finden und zu klicken
            button = driver.find_element(By.XPATH, "//button[contains(@class, 'button') and .//span[text()='Save']]")
            button.click()
        except:
            try:
                # Fallback: Versuche, das Element mit absolutem XPath zu finden und zu klicken
                button = driver.find_element(By.XPATH, "/html/body/div[2]/div[2]/div/div[2]/button[2]")
                button.click()
            except Exception as e:
                print(f"Element konnte nicht gefunden oder angeklickt werden: {e}")

def click_novels_and_stories_span(driver):
    try:
        # Versuche, das Element mit CSS-Path zu finden und zu klicken
        span_element = driver.find_element(By.CSS_SELECTOR, "fieldset.radio-button:nth-child(1) > label:nth-child(1) > span:nth-child(3)")
        span_element.click()
    except:
        try:
            # Fallback: Versuche, das Element mit absolutem XPath zu finden und zu klicken
            span_element = driver.find_element(By.XPATH, "/html/body/div[2]/div[2]/div/div[1]/div[2]/div[2]/div[2]/fieldset[1]/label/span[1]")
            span_element.click()
        except Exception as e:
            print(f"Element konnte nicht gefunden oder angeklickt werden gligluizguk: {e}")
        try:
            # Fallback: Versuche, das Element mit relativem XPath und schwachen Bedingungen zu finden und zu klicken
            span_element = driver.find_element(By.XPATH, "//span[contains(@class, 'radio-symbol')]")
            span_element.click()
        except Exception as e:
            print(f"Element konnte nicht gefunden oder angeklickt werdenälkälköi: {e}")
        try:
            # Fallback: Versuche, das Element mit relativem XPath zu finden und zu klicken
            span_element = driver.find_element(By.XPATH, "//span[contains(text(), 'Novels')]")
            span_element.click()
        except:
            try:
                # Fallback: Versuche, das Element mit absolutem XPath zu finden und zu klicken
                span_element = driver.find_element(By.XPATH, "/html/body/div[2]/div[2]/div/div[1]/div[2]/div[2]/div[2]/fieldset[1]/label/span[1]")
                span_element.click()
            except Exception as e:
                print(f"Element konnte nicht gefunden oder angeklicktljhljhgljhgljhg werden: {e}")

def click_add_genre_button(driver):
    try:
        # Versuche, das Element mit CSS-Path zu finden und zu klicken
        button = driver.find_element(By.CSS_SELECTOR, "div.gap-03:nth-child(2) > div:nth-child(2) > div:nth-child(1) > button:nth-child(2) > div:nth-child(1)")
        button.click()
    except:
        try:
            # Fallback: Versuche, das Element mit relativem XPath zu finden und zu klicken
            button = driver.find_element(By.XPATH, "//div[contains(@class, 'button__inner') and text()='Add Genre']")
            button.click()
        except:
            try:
                # Fallback: Versuche, das Element mit absolutem XPath zu finden und zu klicken
                button = driver.find_element(By.XPATH, "/html/body/div[2]/div[2]/div/div[1]/div[2]/div[2]/div/button/div")
                button.click()
            except Exception as e:
                print(f"Element konnte nicht gefunden oder angeklickt werden: {e}")

def click_detailsbox_button(driver):
    try:
        # Versuche, das Element mit CSS-Selektor zu finden und zu klicken
        button = driver.find_element(By.CSS_SELECTOR, ".detailsbox__absolute-btn")
        button.click()
    except:
        try:
            # Fallback: Versuche, das Element mit relativem XPath zu finden und zu klicken
            button = driver.find_element(By.XPATH, "//button[contains(@class, 'detailsbox')]")
            button.click()
        except: 
            try:
                # Fallback: Versuche, das Element mit absolutem XPath zu finden und zu klicken
                button = driver.find_element(By.XPATH, "/html/body/div[1]/div[3]/div/section/section/div[1]/div[1]/article/div/button")
                button.click()
            except Exception as e:
                print(f"Element konnte nicht gefunden oder angeklickt werden: {e}")


def click_done_button(driver):
    """Versucht, den 'Done'-Button beim Bildupload zu finden und zu klicken."""
    try:
        done_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".modal__footer__actions > button:nth-child(2)"))
        )
        done_button.click()
        return True
    except Exception as e:
        print(f"Fehlgeschlagen: CSS-Selektor: nth-child -> {e}")
    
    return False


def upload_image(driver, image_url):
    """Versucht, das Upload-Element zu finden und die Datei von einer URL hochzuladen."""
    try:
        # Warte und finde das Element
        file_input = WebDriverWait(driver, 20).until(
            EC.presence_of_element_located((By.XPATH, "//input[@type='file']"))
        )
        # Datei von URL herunterladen und temporär speichern
        response = requests.get(image_url)
        temp_file_path = "/tmp/temp_image.jpg"
        with open(temp_file_path, 'wb') as temp_file:
            temp_file.write(response.content)
        
        # Erhöhe die Bildqualität stark
        with Image.open(temp_file_path) as img:
            img = img.resize((img.width * 2, img.height * 2), Image.LANCZOS)
            img.save(temp_file_path, dpi=(400, 400))
        
        # Datei hochladen
        file_input.send_keys(temp_file_path)
        return True
    except Exception as e:
        print(f"Fehlgeschlagen: XPath mit `type='file'` -> {e}")

# Funktion zum Versuch, auf den Upload-Tab zu klicken
def click_upload_tab(driver):
    try:
        upload_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, "//a[@role='tab' and text()='Upload']"))
        )
        upload_button.click()
    except Exception as e:
        print(f"Fehlgeschlagen: XPath mit Textinhalt -> {e}")


def close_popup_if_present(driver):
    try:
        close_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".overlay__close"))
        )
        close_button.click()
    except:
        pass

if __name__ == "__main__":
    for i in range(1):
        try:
            #Beginn des Codes
            book_description = "Schreibe über "
            print(book_description) 
            if book_description== None:
                continue
            
            
            chapter_title = generate_chapter_title(book_description)
            
            print(chapter_title)

            # Beispiel: Generiere einen kurzen Plot
            short_plot = generate_short_plot(book_description)
            short_plot = short_plot.replace('\n\n', '\n')
            print(short_plot)

            bild= generate_image_from_prompt(chapter_title, client)
            # Set up the driver
            os.environ['PATH'] += ':/opt/homebrew/bin'
            driver = webdriver.Chrome()
            driver.get("https://www.story.one/en/")
            driver.maximize_window()

            time.sleep(1)

            # Warte auf den Login-Button und finde ihn mit dem passenden XPath
            login_button =driver.find_element(By.XPATH, "//span[@class='button__label' and text()='Login/Signup']")
            login_button.click()
            # time.sleep(1)
            email_input = WebDriverWait(driver, 10).until(
                EC.presence_of_element_located((By.XPATH, "//input[@name='login-email']"))
            )
            placeholder_email = os.getenv("EMAIL")  # Platzhalter-E-Mail
            email_input.send_keys(placeholder_email)
            time.sleep(1)

            # Warte auf das Passwort-Eingabefeld und finde es mit dem passenden XPath
            password_input = WebDriverWait(driver, 10).until(
                EC.presence_of_element_located((By.XPATH, "//input[@name='login-password']"))
            )

            # Passwort in das Eingabefeld eintippen (Beispiel-Passwort)
            placeholder_password = os.getenv("PASSWORD")  # Platzhalter-Passwort
            password_input.send_keys(placeholder_password)
            time.sleep(1)

            # Warte auf den Login-Button und finde ihn mit XPath
            login_button = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable((By.XPATH, "//span[@class='button__label' and text()='Login']"))
            )

            # Login-Button klicken
            login_button.click()

            time.sleep(5)


            # Warte auf das Cookies-Element und finde es mit dem absoluten XPath
            button = WebDriverWait(driver, 5).until(
                EC.element_to_be_clickable((By.XPATH, "/html/body/div/section/div/div[2]/button[2]"))
            )

            # Button klicken
            button.click()


            # Warte auf das Draft-Element und finde es mit dem absoluten XPath
            button = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable((By.XPATH, "/html/body/div/div[4]/div/div/div[2]/div[1]/div[3]/a/div/span"))
            )

            # Button klicken
            button.click()
            # Warte auf das Element und finde es mit dem absoluten XPath
            try:
                button = WebDriverWait(driver, 10).until(
                    EC.element_to_be_clickable((By.XPATH, "/html/body/div/div[4]/div/div[2]/div/div/div/section[4]/div/div/fieldset/div/div[3]/label/span[2]"))
                )
                # Button klicken
                button.click()
            except:
                try:
                    button = WebDriverWait(driver, 10).until(
                        EC.element_to_be_clickable((By.XPATH, "//span[@data-v-f67ac2ca='' or contains(@class, 'radio-button-option__label__text') or text()='Stories']"))
                    )
                    # Button klicken
                    button.click()
                except Exception as e:
                    print(f"Element konnte nicht gefunden oder angeklickt werden: {e}")
            try:
                # Warte auf den "Story schreiben" Button und finde ihn mit dem absoluten XPath
                # Call the function to close the popup if it appears
                #close_popup_if_present(driver)
                story_button = WebDriverWait(driver, 5).until(
                    EC.element_to_be_clickable((By.XPATH, "/html/body/div/div[4]/div/div[2]/div/div/div/section[4]/div[2]/div[2]/a[1]/div/span"))
                )
                # "Story schreiben" Button klicken
                story_button.click()
            except:
                # Call the function to close the popup if it appears
                #close_popup_if_present(driver)
                # Falls der "Story schreiben" Button nicht gefunden wird, klicke stattdessen auf den angegebenen Link
                alternative_button = WebDriverWait(driver, 5).until(
                    EC.element_to_be_clickable((By.XPATH, "//a[contains(@class, 'book-card__main-anchor')]"))
                )
                alternative_button.click()

            close_popup_if_present(driver)

            # Warte auf das Titelfeld und finde es mit dem absoluten XPath
            title_input = WebDriverWait(driver, 10).until(
                EC.presence_of_element_located((By.XPATH, "//textarea[@name='Title']"))
            )
            # Lösche den Inhalt des Titelfeldes, falls vorhanden
            title_input.clear()
            # Schreibe den Titel in das Textfeld
            title_input.send_keys(chapter_title)

            # Drücke um die eigentliche Story zu schreiben
            try:
                # Warte auf das Element und finde es mit dem passenden CSS-Selektor
                element = WebDriverWait(driver, 10).until(
                    EC.element_to_be_clickable((By.XPATH, "/html/body/div/div[3]/div/section/section/div[1]/div[2]/div[3]/div/div/button"))
                )
            except:
                # Falls das Element nicht gefunden wird, verwende den ursprünglichen CSS-Selektor
                element = WebDriverWait(driver, 10).until(
                    EC.element_to_be_clickable((By.XPATH, "/html/body/div[1]/div[3]/div/section/section/div[1]/div[2]/div[3]/div/div/button"))
                )
            time.sleep(1)
            # Element klicken
            element.click()

            # Warte auf das Textfeld und finde es mit dem passenden XPath
            try:
                story_textarea = WebDriverWait(driver, 20).until(
                    EC.presence_of_element_located((By.XPATH, "/html/body/div[1]/div[3]/div/section/div/div[2]/div[2]/div[2]/div[2]/p"))
                )
            except Exception:
                try:
                    story_textarea = WebDriverWait(driver, 20).until(
                        EC.presence_of_element_located((By.XPATH, "/html/body/div[1]/div[3]/div/section/div/div[2]/div[2]/div[2]"))
                    )
                except Exception:
                    story_textarea = WebDriverWait(driver, 20).until(
                        EC.presence_of_element_located((By.XPATH, "/html/body/div[1]/div[3]/div/section/div/div[2]/div[2]/div[2]/div[2]"))
                    )

            story_textarea.clear()
            story_text = short_plot

            # Teile den Text in kleinere Abschnitte auf
            chunk_size = 1000
            for i in range(0, len(story_text), chunk_size):
                story_textarea.send_keys(story_text[i:i + chunk_size])
                time.sleep(1)  # Kurze Pause zwischen den Eingaben, um die Seite nicht zu überlasten

            #Back Button
            back_button = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable((By.XPATH, "//span[@class='button__label' and text()='Back']"))
            )
            back_button.click()
            # Scroll to the top of the page
            driver.execute_script("window.scrollTo(0, 0);")
            time.sleep(2)
            #Bild hochladen
            try:
                # Zuerst mit CSS-Selektor versuchen
                button = driver.find_element(By.CSS_SELECTOR, ".edit-image-button__button.edit-image-button__button--edit.text-light")
            except:
                try:
                    # Falls der CSS-Selektor nicht funktioniert, mit XPath versuchen
                    button = driver.find_element(By.XPATH, "/html/body/div/div[3]/div/section/section/div[1]/header/div[2]/button")
                except Exception as e:
                    print(f"Element konnte nicht gefunden werden: {e}")
            time.sleep(2)
            try:
                button.click()
            except Exception as e:
                print(f"Element konnte nicht angeklickt werden: {e}")


            click_upload_tab(driver)


            file_path = bild

                    # Upload versuchen
            if upload_image(driver, file_path):
                pass
            else:
                print("Datei-Upload ist fehlgeschlagen.")

            click_done_button(driver)

            time.sleep(20)
            click_detailsbox_button(driver)

            click_add_genre_button(driver)
            time.sleep(3)
            click_novels_and_stories_span(driver)
            time.sleep(3)
            click_save_button(driver)
            time.sleep(10)
            click_share_on_storyone_button(driver)

            # Warte 50 Sekunden, bevor der Browser geschlossen wird
            time.sleep(10)
            driver.quit()
        except Exception as e:
            print(f"Fehler: {e}")
            time.sleep(60)
            pass