# Generated by Selenium IDE
import time
import os
import random
import requests
from playwright.sync_api import sync_playwright
from openai import OpenAI
from PIL import Image
from dotenv import load_dotenv

#Keys

load_dotenv()

# Lade Umgebungsvariablen aus der .env-Datei
openai_key = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=openai_key) if openai_key else None

def fetch_random_wikipedia_summary():
    """Fetch a random article summary from German Wikipedia."""
    try:
        response = requests.get(
            "https://de.wikipedia.org/api/rest_v1/page/random/summary", timeout=10
        )
        if response.status_code == 200:
            data = response.json()
            return data.get("extract", "")
    except Exception as exc:
        print(f"Fehler beim Abrufen der Wikipedia-Zusammenfassung: {exc}")
    return ""


def download_image(url: str, path: str) -> None:
    """Download image from the given URL to the specified path."""
    try:
        resp = requests.get(url, timeout=30)
        resp.raise_for_status()
        with open(path, "wb") as f:
            f.write(resp.content)
    except Exception as exc:
        raise RuntimeError(f"Bild konnte nicht heruntergeladen werden: {exc}")

# def generate_random_keywords(n=50):
#     """
#     Generiert eine Liste von n zufälligen deutschen Wörtern.
    
#     :param n: Anzahl der zu generierenden Wörter.
#     :return: Liste von Wörtern.
#     """
#     url = "https://random-word-api.herokuapp.com/word"
#     params = {"number": n, "lang": "de"}
#     response = requests.get(url, params=params)
    
#     if response.status_code == 200:
#         words = response.json()
#         return words
#     else:
#         print(f"Fehler: {response.status_code} - {response.text}")
#         return []

# Funktion zum Generieren eines Bildes aus einem Textprompt
def generate_image_from_prompt(short_plot, client=None):
    """Generate an image from DALL-E based on the short plot."""
    client = client or (OpenAI(api_key=os.getenv("OPENAI_API_KEY")) if os.getenv("OPENAI_API_KEY") else None)
    if client is None:
        raise RuntimeError("OPENAI_API_KEY is not configured")

    response = client.images.generate(
        model="dall-e-3",  # Bestes verfügbares Bildgenerierungsmodell
        prompt=f"""Erstelle ein künstlerisches, hochwertiges Bild basierend auf dieser Geschichte: {short_plot}
        
        Wichtige Anforderungen:
        - Keine Texte oder Wörter im Bild
        - Fokussiere auf die wichtigste Szene oder den emotionalsten Moment
        - Verwende eine ansprechende Komposition
        - Achte auf Details und Atmosphäre
        - Wähle passende Farben und Stimmung
        - Erstelle ein Bild im Stil eines professionellen Buchcovers
        - Stelle sicher, dass das Bild die Essenz der Geschichte einfängt""",
        size="1024x1024",
        quality="standard",
        n=1,
    )
    image_url = response.data[0].url
    print(f"Bild-URL: {image_url}")
    return image_url
    


def generate_chapter_title(story_description, client=None):
    """Generate a catchy title for the given story description."""
    client = client or (OpenAI(api_key=os.getenv("OPENAI_API_KEY")) if os.getenv("OPENAI_API_KEY") else None)
    if client is None:
        raise RuntimeError("OPENAI_API_KEY is not configured")

    completion = client.chat.completions.create(
        model="gpt-4-1106-preview",  # GPT-4 Turbo
        messages=[
            {"role": "system", "content": """Du bist ein Experte für kreative Titel.
            Deine Titel sind:
            - Einprägsam und originell
            - Neugierig machend
            - Passend zum Inhalt
            - Nicht zu lang
            - Mit emotionalem Impact
            
            Ein guter Titel sollte:
            - Die Essenz der Geschichte einfangen
            - Neugier wecken
            - Zum Weiterlesen anregen
            - Die Stimmung der Geschichte widerspiegeln"""},
            {
                "role": "user",
                "content": f"""Generiere einen fesselnden Titel für eine Geschichte basierend auf: {story_description}
                
                Wichtige Anforderungen:
                - Maximal 6 Wörter
                - Keine Anführungszeichen
                - Nur Wörter aus der Beschreibung verwenden
                - Der Titel soll neugierig machen
                - Der Titel soll die Stimmung der Geschichte einfangen
                - Der Titel soll zum Inhalt passen
                - Der Titel soll emotional ansprechend sein"""
            }
        ]
    )
    return completion.choices[0].message.content


def generate_short_plot(story_description, client=None):
    """Create a short plot using GPT based on the story description."""
    client = client or (OpenAI(api_key=os.getenv("OPENAI_API_KEY")) if os.getenv("OPENAI_API_KEY") else None)
    if client is None:
        raise RuntimeError("OPENAI_API_KEY is not configured")

    completion = client.chat.completions.create(
        model="gpt-4-1106-preview",  # GPT-4 Turbo
        messages=[
            {"role": "system", "content": """Du bist ein erfahrener Geschichtenerzähler mit folgenden Fähigkeiten:
            - Erstellung fesselnder Geschichten mit klarer Struktur
            - Entwicklung lebendiger Charaktere
            - Schreiben natürlicher Dialoge
            - Aufbau von Spannung und Emotion
            - Schaffen einer immersiven Atmosphäre
            
            Deine Geschichten folgen dieser Struktur:
            1. Einleitung: Einführung der Hauptfigur und des Settings
            2. Aufbau: Entwicklung des Konflikts oder der Herausforderung
            3. Höhepunkt: Die entscheidende Wendung oder Aktion
            4. Auflösung: Eine befriedigende Lösung oder Erkenntnis
            
            Stilistische Merkmale:
            - Lebendige Beschreibungen
            - Abwechslungsreiche Satzlängen
            - Authentische Dialoge
            - Emotionale Tiefe
            - Klare Absätze für bessere Lesbarkeit"""},
            {
                "role": "user",
                "content": f"""Erstelle eine fesselnde Geschichte basierend auf: {story_description}
                
                Wichtige Anforderungen:
                - Schreibe maximal 400 Wörter
                - Verwende die vorgegebene Struktur (Einleitung, Aufbau, Höhepunkt, Auflösung)
                - Erstelle mindestens einen interessanten Charakter mit Persönlichkeit
                - Baue mindestens einen natürlichen Dialog ein
                - Beschreibe die Umgebung und Stimmung detailliert
                - Verwende verschiedene Satzlängen für einen flüssigen Lesefluss
                - Teile den Text in sinnvolle Absätze
                - Baue Spannung auf
                - Achte auf einen logischen Handlungsverlauf
                - Verwende bildhafte Sprache
                - Schreibe in einem leicht lesbaren, aber ansprechenden Stil"""
            }
        ]
    )
    return completion.choices[0].message.content


def generate_story_prompt():
    """
    Generiert einen kohärenten, aber zufälligen Story-Prompt.
    Kombiniert verschiedene Elemente zu einer interessanten Geschichte.
    Deckt alle Genres ab: Sci-Fi, Fantasy, Krimi, Thriller, Drama, Komödie, etc.
    """
    # Verschiedene Story-Elemente
    settings = [
        # Moderne Settings
        "in einem trendigen Co-Working Space", "in einer versteckten Bar", "in einem Luxushotel",
        "in einem verlassenen Einkaufszentrum", "in einem U-Bahn-Tunnel", "in einem Hochhaus",
        "in einem verschneiten Skigebiet", "in einem überfüllten Flughafen", "in einem geheimen Labor",
        "in einem versteckten Bunker", "in einem alten Kino", "in einem verlassenen Vergnügungspark",
        
        # Sci-Fi Settings
        "auf einer Raumstation", "in einer virtuellen Realität", "in einer alternativen Zukunft",
        "in einer künstlichen Intelligenz", "in einer Quantenwelt", "in einer Zeitmaschine",
        "auf einem fremden Planeten", "in einer Dystopie", "in einer post-apokalyptischen Welt",
        
        # Fantasy Settings
        "in einer magischen Dimension", "in einem verzauberten Wald", "in einer Unterwasserwelt",
        "in einer Parallelwelt", "in einem magischen Königreich", "in einer mythischen Stadt",
        
        # Natur Settings
        "in einem tropischen Regenwald", "in einer Wüste", "auf einem Gletscher",
        "in einem Korallenriff", "in einer Höhle", "auf einem Vulkan",
        
        # Urban Settings
        "in einer Großstadt", "in einem Vorort", "in einem Slum",
        "in einem Nobelviertel", "in einem Industriegebiet", "in einem Hafen"
    ]
    
    characters = [
        # Moderne Charaktere
        "ein erfolgreicher Tech-Entrepreneur", "eine investigative Journalistin", "ein genialer Hacker",
        "eine berühmte Influencerin", "ein mysteriöser Künstler", "ein ehemaliger Spion",
        "eine ambitionierte Anwältin", "ein verrückter Wissenschaftler", "eine mutige Aktivistin",
        "ein talentierter Musiker", "ein geheimnisvoller Detektiv", "eine geniale Programmiererin",
        
        # Alltagscharaktere
        "ein Taxifahrer", "eine Barista", "ein Postbote",
        "eine Krankenschwester", "ein Lehrer", "ein Koch",
        
        # Ungewöhnliche Charaktere
        "ein Zeitreisender", "ein Alien", "ein Android",
        "ein Geist", "ein Mutant", "ein Superheld",
        
        # Professionelle Charaktere
        "ein Chirurg", "ein Architekt", "ein Psychologe",
        "ein Polizist", "ein Politiker", "ein Anwalt"
    ]
    
    conflicts = [
        # Moderne Konflikte
        "muss eine Verschwörung aufdecken", "kämpft gegen eine KI-Bedrohung", "versucht einen Hackerangriff zu stoppen",
        "muss ein Unternehmen retten", "kämpft gegen Korruption", "versucht eine Pandemie zu verhindern",
        "muss eine Geheimwaffe zerstören", "kämpft gegen Cyberkriminalität", "versucht eine Revolution zu starten",
        
        # Persönliche Konflikte
        "muss eine schwierige Entscheidung treffen", "kämpft gegen eine Sucht", "versucht eine Beziehung zu retten",
        "muss mit einem Trauma umgehen", "kämpft gegen Vorurteile", "versucht sich selbst zu finden",
        
        # Gesellschaftliche Konflikte
        "muss gegen Ungerechtigkeit kämpfen", "versucht die Umwelt zu retten", "kämpft für Menschenrechte",
        "muss eine Gemeinschaft retten", "versucht Frieden zu stiften", "kämpft gegen Diskriminierung",
        
        # Übernatürliche Konflikte
        "muss ein magisches Artefakt finden", "kämpft gegen eine dunkle Macht", "versucht die Zeit zu ändern",
        "muss ein Portal schließen", "kämpft gegen ein Monster", "versucht eine Prophezeiung zu erfüllen"
    ]
    
    themes = [
        # Moderne Themen
        "über Technologie und Menschlichkeit", "über Social Media und Identität", "über Klimawandel und Verantwortung",
        "über künstliche Intelligenz und Ethik", "über Globalisierung und Kultur", "über Digitalisierung und Privatsphäre",
        
        # Gesellschaftliche Themen
        "über Macht und Korruption", "über Gerechtigkeit und Gleichheit", "über Freiheit und Sicherheit",
        "über Tradition und Fortschritt", "über Individualität und Konformität", "über Armut und Reichtum",
        
        # Persönliche Themen
        "über Liebe und Verlust", "über Freundschaft und Verrat", "über Familie und Identität",
        "über Träume und Realität", "über Vergangenheit und Zukunft", "über Leben und Tod",
        
        # Philosophische Themen
        "über Gut und Böse", "über Wahrheit und Lüge", "über Schicksal und freier Wille",
        "über Realität und Illusion", "über Wissen und Weisheit", "über Glaube und Wissenschaft"
    ]
    
    # Zufällige Auswahl der Elemente
    setting = random.choice(settings)
    character = random.choice(characters)
    conflict = random.choice(conflicts)
    theme = random.choice(themes)
    
    # Zusammenstellung des Prompts
    prompt = f"Eine Geschichte {setting}, in der {character} {conflict} {theme}."
    
    return prompt

if __name__ == "__main__":
    for _ in range(1):
        try:
            # Eine zufällige Beschreibung aus Wikipedia holen
            book_description = fetch_random_wikipedia_summary()
            if not book_description:
                print("Keine Beschreibung erhalten, überspringe Lauf.")
                continue

            chapter_title = generate_chapter_title(book_description, client)
            short_plot = generate_short_plot(book_description, client)
            bild = generate_image_from_prompt(short_plot, client)

            print(f"Prompt: {book_description}")
            print(f"Titel: {chapter_title}")
            print(f"Geschichte:\n{short_plot}")
            
            # Playwright Setup
            slow_mo_value = 500 if os.getenv("PLAYWRIGHT_SLOWMO") == "1" else None

            browser = None
            try:
                with sync_playwright() as p:
                    browser = p.chromium.launch(headless=False, slow_mo=slow_mo_value)
                    context = browser.new_context()
                    page = context.new_page()
                    
                    # Navigate to StoryOne
                    page.goto("https://www.story.one/en/")
                    page.set_viewport_size({"width": 1920, "height": 1080})

                    # Login
                    page.click("text=Login/Signup")
                    page.fill("input[name='login-email']", os.getenv("EMAIL"))
                    page.fill("input[name='login-password']", os.getenv("PASSWORD"))
                    page.click("text=Login")
                    page.wait_for_load_state("networkidle")

                    # Handle cookies if present
                    try:
                        page.click("button:has-text('Accept')", timeout=5000)
                    except:
                        pass

                    # Click on draft
                    page.click("text=Draft")
                    page.wait_for_load_state("networkidle")

                    # Select story type
                    try:
                        page.click("text=Stories")
                    except:
                        page.click("span:has-text('Stories')")
                    page.wait_for_load_state("networkidle")

                    # Click write story
                    try:
                        page.click("text=Write Story")
                    except:
                        page.click("a:has-text('Write Story')")
                    page.wait_for_load_state("networkidle")

                    # Fill in title
                    page.fill("textarea[name='Title']", chapter_title)

                    # Click to write story
                    page.click("button:has-text('Write')")
                    page.wait_for_load_state("networkidle")

                    # Fill in story content
                    page.fill("div[contenteditable='true']", short_plot)
                    page.keyboard.press("Control+A")
                    page.keyboard.press("Control+C")
                    page.keyboard.press("Control+V")

                    # Go back
                    page.click("text=Back")
                    page.wait_for_load_state("networkidle")

                    # Upload image
                    page.click("button.edit-image-button__button")
                    page.click("text=Upload")

                    temp_file_path = "/tmp/story_image.jpg"
                    download_image(bild, temp_file_path)

                    # Upload the image
                    page.set_input_files("input[type='file']", temp_file_path)
                    page.click("text=Done")
                    page.wait_for_load_state("networkidle")

                    # Add genre
                    page.click("button:has-text('Add Genre')")
                    page.click("text=Novels and Stories")
                    page.click("button:has-text('Save')")
                    page.wait_for_load_state("networkidle")

                    # Share on StoryOne
                    page.click("button:has-text('Share on StoryOne')")
                    page.wait_for_load_state("networkidle")

                    # Logout
                    try:
                        page.click("text=Logout")
                        page.wait_for_load_state("networkidle")
                    except Exception:
                        pass

                    # Wait before closing
                    time.sleep(10)
                    print("Browser wird geschlossen...")
                    browser.close()
            except Exception as e:
                print(f"Fehler: {e}")
                if browser:
                    print("Browser wird geschlossen...")
                    browser.close()

        except Exception as e:
            print(f"Fehler: {e}")
            time.sleep(60)
            pass

